# Generated by Django 3.0.4 on 2020-04-01 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200329_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 1, 22, 37, 11, 301196)),
        ),
    ]
