# Generated by Django 3.0.4 on 2020-04-07 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200401_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 20, 46, 55, 144406)),
        ),
    ]
