# Generated by Django 3.0.4 on 2020-03-20 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('availability', models.IntegerField()),
                ('title', models.CharField(default='NA', max_length=255)),
                ('price', models.PositiveIntegerField(default=0)),
                ('authors', models.ManyToManyField(to='LibraryMS.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pub_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LibraryMS.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LibraryMS.Publisher'),
        ),
    ]
